# To use this lab configuration, add the following line to your configuration.yaml:
#homeassistant:
#  packages:
#    compliance_lab: !include compliance_manager_lab_sensors.yaml

switch:
  - platform: compliance_manager
    test_mode:                true
    test_groups_to_create:    40
    show_cleanup_lab_service: true

binary_sensor:
  - platform: compliance_manager
    show_debug_attributes: true
    sensors:
# Test 01: AND/OR/NOT Test; Expoff (switches) OR is problem, but with <= 2 violations (lab_test_output_02)
      - name: "Lab Test Output 01"
        alias: "Lab Test Output 01: Comprehensive Logic Check"
        unique_id: cm_lab_test_01
        compliance_rules:
          - alias: "Main Rule: Comprehensive Logic Check"
            target:
              entity_id:
                - switch.compliance_manager_lab_tester_1
                - switch.compliance_manager_lab_tester_2
                - switch.compliance_manager_lab_tester_3
                - switch.compliance_manager_lab_tester_4
                - binary_sensor.lab_test_output_02
            and:
              - alias: "Is compliant if: OPT.A) either is a switch off, or is a binary_sensor with active_count <= 2"
                or:
                - alias:   "Ok if switch is off (switch does not have active_count attrib)"
                  value_template: >
                                  {{  is_state(t_id, 'off')  and
                                      is_state(t_entity.entity_id,  'off') and
                                      t_state == 'off'  and
                                     ( states(t_id) is not none and 'active_count' not in states[t_id].attributes ) 
                                   }}
                - alias: "ok if binary_sensor with active_count == 1 or  2 "
                  target:
                    entity_id:
                      - binary_sensor.lab_test_output_02
                  and:
                  - alias: "Invert Target State"
                    not:
                    - alias: "Check Target State"
                      expected_state: "off"
                  - alias: "Check Self-Active Count"
                    attribute: "active_count"
                    expected_numeric:
                      min: 0
                      max: 1


      # Test 02: Stato OFF con Grace Period
      - name: "Lab Test Output 02"
        alias: "# Test 02: Exp OFF with 3sec Grace Period (entity 1  only used if added to label_test_02 and entity 2 if added to areas-kitchen"
        unique_id: cm_lab_test_02
        compliance_rules:
          - target:
              label_id:
                label_test_02 #- switch.compliance_manager_lab_tester_5
              area_id:
                areas-kitchen #- switch.compliance_manager_lab_tester_6
              entity_id:
                - switch.compliance_manager_lab_tester_7
                - switch.compliance_manager_lab_tester_8
            expected_state: "off"
            grace_period: "00:00:03"
            severity: warning

      # Test 3: Logica hardcoded
      - name: "Lab Test Output 03"
        alias: "# Test 03: on ONLY if switch1 2 qnd 3 are On but switch4 Off (switch4 hardcoded)"
        unique_id: cm_lab_test_03
        compliance_rules:
          - target:
              entity_id:
                - switch.compliance_manager_lab_tester_9
                - switch.compliance_manager_lab_tester_10
                - switch.compliance_manager_lab_tester_11
                - switch.compliance_manager_lab_tester_12
            value_template: >
                  {% set hardcoded_sensor = 'switch.compliance_manager_lab_tester_12' %}
                  {% set off_reference = is_state(hardcoded_sensor, 'off') %}
                  {% set is_on =  is_state(t_id, 'on')  or t_id == hardcoded_sensor  %}
                  {{ is_on and is_state('switch.compliance_manager_lab_tester_12', 'off') }}

      # Test 4: Logica OR con severità critica
      - alias: "est 04: Reboot Persistence: Exp On/Off, Grace 5min (1st switch) or 5 sec, add a 5min snooze to test that too"
        name: "Lab Test Output 04"
        unique_id: cm_lab_test_04
        compliance_rules:
          - target:
              entity_id:
                - switch.compliance_manager_lab_tester_13
            or:
                - expected_state: "on"
                - expected_state: "off"
            grace_period:
              minutes: 5
            severity: "critical"
          - target:
              entity_id:
                - switch.compliance_manager_lab_tester_14
                - switch.compliance_manager_lab_tester_15
                - switch.compliance_manager_lab_tester_16
            condition:
              - or:
                - expected_state: "on"
                - expected_state: "off"
            grace_period:
              seconds: 5
            severity: "critical"

      # Test 5: Logica NOT
      - name: "Lab Test Output 05"
        unique_id: cm_lab_test_05
        compliance_rules:
          - target:
              entity_id:
                - switch.compliance_manager_lab_tester_17
                - switch.compliance_manager_lab_tester_18
                - switch.compliance_manager_lab_tester_19
                - switch.compliance_manager_lab_tester_20
            not:
                 - expected_state: "off"

      # Test 6: Permetti Unavailable con severità numerica
      - name: "Lab Test Output 06"
        unique_id: cm_lab_test_06
        compliance_rules:
          - target:
              entity_id:
                - switch.compliance_manager_lab_tester_21
                - switch.compliance_manager_lab_tester_22
                - switch.compliance_manager_lab_tester_23
                - switch.compliance_manager_lab_tester_24
            expected_state: "on"
            allow_unavailable: true
            severity:
              level: 8
              label: "Warning Low"

      # Test 7: Group Grace attivo
      - name: "Lab Test Output 07"
        unique_id: cm_lab_test_07
        compliance_rules:
          - target:
              entity_id:
                - switch.compliance_manager_lab_tester_25
                - switch.compliance_manager_lab_tester_26
                - switch.compliance_manager_lab_tester_27
                - switch.compliance_manager_lab_tester_28
            expected_state: "on"
            group_grace: true
            grace_period: "00:00:20"

      # Test 8: Value Template complesso
      - name: "Lab Test Output 08"
        unique_id: cm_lab_test_08
        compliance_rules:
          - target:
              entity_id:
                - switch.compliance_manager_lab_tester_29
                - switch.compliance_manager_lab_tester_30
                - switch.compliance_manager_lab_tester_31
                - switch.compliance_manager_lab_tester_32
            value_template: "{{ states(t_id) == 'on' and t_state == 'on' and states(t_entity.entity_id) == 'on' }}"


      # Test 9: Permetti Unknown
      - name: "Lab Test Output 09"
        unique_id: cm_lab_test_09
        compliance_rules:
          - target:
              entity_id:
                - switch.compliance_manager_lab_tester_33
                - switch.compliance_manager_lab_tester_34
                - switch.compliance_manager_lab_tester_35
                - switch.compliance_manager_lab_tester_36
            expected_state: "on"
            allow_unknown: true

      # Test 10: Combinazione finale AND/NOT con severità massima
      - name: "Lab Test Output 10"
        unique_id: cm_lab_test_10
        compliance_rules:
          - target:
              entity_id:
                - switch.compliance_manager_lab_tester_37
                - switch.compliance_manager_lab_tester_38
                - switch.compliance_manager_lab_tester_39
                - switch.compliance_manager_lab_tester_40
            and:
                - expected_state: "on"
                - not:
                    - expected_state: "off"
            severity:
              level: 10
              label: "No Panic"